*** Starting uWSGI 2.0.15 (64bit) on [Mon Dec 25 18:13:30 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 25 December 2017 17:58:35
os: Linux-3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017
nodename: iZrj9acq02ar6zvxx6ovrcZ
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /var/www/django-web/pics
writing pidfile to /var/www/django-web/pics/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/django-web/pics/
your processes number limit is 3895
your memory page size is 4096 bytes
detected max file descriptor number: 65535
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
bind(): Cannot assign requested address [core/socket.c line 769]
*** Starting uWSGI 2.0.15 (64bit) on [Mon Dec 25 18:15:22 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 25 December 2017 17:58:35
os: Linux-3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017
nodename: iZrj9acq02ar6zvxx6ovrcZ
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /var/www/django-web/pics
writing pidfile to /var/www/django-web/pics/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/django-web/pics/
your processes number limit is 3895
your memory page size is 4096 bytes
detected max file descriptor number: 65535
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI http bound on 127.0.0.1:80 fd 3
uwsgi socket 0 bound to UNIX address /var/www/django-web/pics/script/uwsgi.sock fd 6
Python version: 3.6.3 (default, Nov 17 2017, 14:43:46)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Python main interpreter initialized at 0x1e6e3b0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 485760 bytes (474 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1e6e3b0 pid: 6322 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6322)
spawned uWSGI worker 1 (pid: 6324, cores: 1)
spawned uWSGI worker 2 (pid: 6325, cores: 1)
spawned uWSGI worker 3 (pid: 6326, cores: 1)
spawned uWSGI worker 4 (pid: 6327, cores: 1)
spawned uWSGI worker 5 (pid: 6328, cores: 1)
spawned uWSGI http 1 (pid: 6329)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view cats.views.index didn't return an HttpResponse object. It returned None instead.
[pid: 6328|app: 0|req: 1/1] 127.0.0.1 () {28 vars in 298 bytes} [Mon Dec 25 18:15:36 2017] GET / => generated 48822 bytes in 72 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.15 (64bit) on [Mon Dec 25 18:24:31 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-16) on 25 December 2017 17:58:35
os: Linux-3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017
nodename: iZrj9acq02ar6zvxx6ovrcZ
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /var/www/django-web/pics
writing pidfile to /var/www/django-web/pics/script/uwsgi.pid
detected binary path: /usr/local/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /var/www/django-web/pics/
your processes number limit is 3895
your memory page size is 4096 bytes
detected max file descriptor number: 65535
!!! no /etc/mime.types file found !!!
lock engine: pthread robust mutexes
thunder lock: enabled
bind(): Cannot assign requested address [core/socket.c line 769]
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view cats.views.index didn't return an HttpResponse object. It returned None instead.
[pid: 6325|app: 0|req: 1/2] 127.0.0.1 () {28 vars in 298 bytes} [Mon Dec 25 18:25:34 2017] GET / => generated 48822 bytes in 68 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Not Found: /pics
[pid: 6326|app: 0|req: 1/3] 183.15.83.54 () {40 vars in 700 bytes} [Mon Dec 25 18:35:54 2017] GET /pics => generated 2979 bytes in 13 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 6324|app: 0|req: 1/4] 183.15.83.54 () {42 vars in 731 bytes} [Mon Dec 25 18:37:43 2017] GET /pics => generated 0 bytes in 6 msecs (HTTP/1.1 301) 3 headers in 111 bytes (1 switches on core 0)
Internal Server Error: /pics/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 198, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view cats.views.index didn't return an HttpResponse object. It returned None instead.
[pid: 6327|app: 0|req: 1/5] 183.15.83.54 () {42 vars in 733 bytes} [Mon Dec 25 18:37:43 2017] GET /pics/ => generated 50174 bytes in 75 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
